
name: Deploy PHP Application to Shared Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Shared Hosting
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Deploy files via FTP
      - name: Deploy to Shared Hosting via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./ # Directory to deploy
          server-dir: ${{ secrets.FTP_PATH }} # Remote server directory

      # Optional: Notify of successful deployment
      - name: Deployment Success
        run: echo "Deployment to shared hosting completed successfully!"
